#!/bin/bash -l
set -e

# Check for terraform credentials
if [ -f /root/.terraform.d/credentials.tfrc.json ]
then 
    echo "Terraform Cloud credentials file found."
else
    echo "No Terraform Cloud credentials file found..."
    terraform login 
fi

# Check for organization variable
if [ -z "${ORG}" ]
then 
    fail-message "No Organization found. Please enter your desired Terraform Cloud Organization as the ORG variable."
    exit 1
else
    # Store the ORG in ~/.bashrc
    echo "export ORG=${ORG}" >> ~/.bashrc
fi

# Check for consul license variable
if [ -z "${CONSUL_LICENSE}" ]
then 
    fail-message "No Consul license found. Please enter your provided Consul license as the CONSUL_LICENSE variable."
    exit 1
else
    # Store the CONSUL_LICENSE in ~/.bashrc
    echo "export CONSUL_LICENSE=${CONSUL_LICENSE}" >> ~/.bashrc
fi

exit 0