#!/bin/bash -l
set -e

# Check for terraform credentials
if [ -f /root/.terraform.d/credentials.tfrc.json ]
then 
    echo "Terraform Cloud credentials file found."
else
    echo "No Terraform Cloud credentials file found..."
    terraform login 
fi

# Check for ORG stored in bashrc 
ORGNAME=$(echo $(tail -2 ~/.bashrc | head -1))
if [ "${ORGNAME}" = "export ORG=" ]; then
  fail-message "Organization variable (ORG) not found in bashrc file."
  exit 1
fi

# Check for ORG stored in bashrc 
CLICENSE=$(echo $(tail -1 ~/.bashrc)
if [ "${CLICENSE}" = "export CONSUL_LICENSE=" ]; then
  fail-message "Consul license variable (CONSUL_LICENSE) not found in bashrc file."
  exit 1
fi

exit 0
