#!/bin/sh

#ip & creds
cd /root/terraform/panw-vm/
firewall_ip=$(echo $(terraform output FirewallIP) | tr -d '"')
pa_username=$(echo $(terraform output pa_username) | tr -d '"')
pa_password=$(echo $(terraform output pa_password) | tr -d '"')

#check fw
pa_addr_group=$(curl -sk -u ${pa_username}:${pa_password} "https://${firewall_ip}/restapi/v9.1/Objects/AddressGroups?location=vsys&vsys=vsys1&name=cts-addr-grp-web" | jq -r '.result.entry[0]["@name"]')
if [ "${pa_addr_group}" != "cts-addr-grp-web" ]; then
  fail-message "Palo Alto VM Series Firewall 'base configuration' not applied. "
  exit 1
fi

exit 0
