#!/bin/bash

#profile
cd /root/terraform/vnet/
bastion_ip=$(echo $(terraform output bastion_ip) | tr -d '"')
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

#dir
set-workdir /root/terraform
cd /root/terraform/

exit 0
