#!/bin/bash

#dir
set-workdir /root/terraform

#profile
bastion_ip=$(echo $(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip) | tr -d '"')
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

exit 0
