#!/bin/bash

echo ""
echo ">>"
echo ">> Validating Consul and Vault"
echo ">>"
cd /root/terraform/vault/
vault_lb=$(echo $(terraform output vault_lb) | tr -d '"')
VAULT_ADDR=http://${vault_lb}
echo $CONSUL_HTTP_ADDR
echo $VAULT_ADDR

exit 0
